### ISSUE TITLE
Feature Request: Add Atom feed with plugin

### ISSUE THREAD

**Issue by Mithras44** [bokeh/blog.bokeh.org#25]
Hi, it would be really helpful to add atom support (similar to RSS) to the blog to make it easier to subscribe to using readers such as feedly. 

There is a plugin for Jekyll [https://github.com/jekyll/jekyll-feed](https://github.com/jekyll/jekyll-feed) that will add this functionality by adding one like to the Gem file:

`gem 'jekyll-feed'`

and another to the _config.yml file:

```
plugins:
  - jekyll-feed
```

The plugin will automatically generate an Atom feed at /feed.xml

I need to learn more on how to use git/github and best practice + etiquette  before I can put in a (pull request?) myself (shouldn't take too long I hope).

**Comment by bryevdv** [comment]
@Mithras44 thanks for the information. Since you seem interested in learning to make a PR, I look forward to merging it in the future. The first step to making a PR is to "fork" the repo using the button at the top of the page. Then you can make changes on your copy of the repo, and make a pull request to propose that they be merged into this repo. Let me know if I can answer any questions.

**Comment by Mithras44** [comment]
By adding the lines above I've got an Atom xml feed on http://localhost:4000/feed.xml although it doesn't have  "style information associated with it". Will do pull requests.

![bokeh blog atom](https://user-images.githubusercontent.com/33360173/50604292-5d14ed00-0eb6-11e9-85a1-c99a95152dda.png)

**Comment by bryevdv** [comment]
@Mithras44 I've merged the first two PRs. Is this issue complete and can be closed now? Thanks for contributing!

**Comment by Mithras44** [comment]
I think so, thanks for replying so quickly.
